// Generated by https://quicktype.io

export interface IQuoteDTO {
  success: ISuccess;
  contents: IContents;
  baseurl: string;
  copyright: ICopyright;
}

export interface IContents {
  quotes: IQuote[];
}

export interface IQuote {
  quote: string;
  length: string;
  author: string;
  tags: string[];
  category: string;
  language: string;
  date: string;
  permalink: string;
  id: string;
  background: string;
  title: string;
}

export interface ICopyright {
  year: number;
  url: string;
}

export interface ISuccess {
  total: number;
}
